[package]
name = "example_derive"
version = "0.1.0"
authors = ["James Andrew <james.andrew@metaswitch.com>"]
license = "MIT"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
quote = "0.6"
syn = "0.15"
